# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: librebooking-${MOLECULE_DISTRO:-ubuntu2604}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        # Helper variables
        librebooking_debug_service_enabled: false

        # Variables for LibreBooking
        librebooking_uid: www-data
        librebooking_gid: www-data
        librebooking_hostname: localhost
        librebooking_container_labels_traefik_enabled: false
        librebooking_container_http_host_bind_port: 8080
        librebooking_environment_variables_lb_install_password: password

        # Variables required for LibreBooking to connect to the MariaDB database
        librebooking_database_hostname: "{{ mariadb_connection_hostname }}"
        librebooking_database_port: "{{ mariadb_connection_port }}"
        librebooking_database_username: my_database_username
        librebooking_database_password: my_database_password
        librebooking_database_name: librebooking
        librebooking_systemd_required_services_list_auto: |
          {{
            (['mariadb.service'])
          }}

        # Variables for MariaDB
        mariadb_uid: 1000
        mariadb_gid: 1000
        mariadb_root_password: mariadb_password
        mariadb_container_network: "{{ librebooking_container_network }}"
        mariadb_managed_databases: |
          {{
            [{
              'name': librebooking_database_name,
              'username': librebooking_database_username,
              'password': librebooking_database_password,
            }]
          }}
  env:
    # Workaround for https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
scenario:
  # See: https://docs.ansible.com/projects/molecule/configuration/?h=test_sequence#scenario
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # Disable idempotence test for now due to ansible-role-mariadb
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
